//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// opencvstudio.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_OPENCVSTUDIO_DIALOG         102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_DLG_IMAGE                   132
#define IDR_MENU2                       134
#define IDD_DLG_FUN_THRESHOLD           135
#define IDD_DLG_FUN_THRESHOLDA          136
#define IDD_DLG_FUN_OPERATION           137
#define IDD_DLG_FUN_CONTRAST            138
#define IDD_DLG_FUN_CVTCOLOR            139
#define IDD_DLG_FUN_FILTER              140
#define IDD_DLG_FUN_MORPHOLOGY          141
#define IDD_DLG_FUN_CUDA                142
#define IDD_DLG_FUN_MATCH               143
#define IDC_MFCBUTTON_FUN_TH            1000
#define IDC_STATIC_IMAGE                1001
#define IDC_MFCBUTTON_FUN_ATH           1001
#define IDC_STATIC_TITLE_SRC            1002
#define IDC_MFCBUTTON_FUN_OPERATION     1002
#define IDC_STATIC_TITLE_DST            1003
#define IDC_MFCBUTTON_FUN_CONTRAST      1003
#define IDC_STATIC_TITLE                1004
#define IDC_MFCBUTTON_FUN_CVTCOLOR      1004
#define IDC_COMBO_SRC                   1005
#define IDC_STATIC_TITLE_SRC2           1005
#define IDC_MFCBUTTON_FUN_FILTER        1005
#define IDC_COMBO_DST                   1006
#define IDC_MFCBUTTON_FUN_MORP          1006
#define IDC_EDIT_TH                     1007
#define IDC_MFCBUTTON_FUN_CUDA          1007
#define IDC_EDIT_MV                     1008
#define IDC_EDIT_CANNY_TH1              1008
#define IDC_MFCBUTTON_FUN_MATCH         1008
#define IDC_COMBO_METHOD                1009
#define IDC_MFCBUTTON_FUN_LABEL         1009
#define IDC_MFCBUTTON_APPLY             1010
#define IDC_MFCBUTTON_FUN_CONTOURS      1010
#define IDC_LIST_LOG                    1011
#define IDC_COMBO_TYPE                  1011
#define IDC_COMBO_METHOD2               1011
#define IDC_EDIT_CANNY_TH2              1011
#define IDC_MFCBUTTON_LOAD              1011
#define IDC_EDIT_BS                     1012
#define IDC_COMBO_SRC1                  1012
#define IDC_MFCBUTTON_FUN_FITLINE       1012
#define IDC_EDIT_C                      1013
#define IDC_COMBO_SRC2                  1013
#define IDC_EDIT_ALPHA                  1013
#define IDC_BUTTON_APPLY_CANNY          1013
#define IDC_MFCBUTTON_FUN_CORNER        1013
#define IDC_EDIT_BETA                   1014
#define IDC_EDIT_EROSION_KERNAL1        1014
#define IDC_MFCBUTTON_FUN_HOUGHLINES    1014
#define IDC_EDIT_EROSION_KERNAL2        1015
#define IDC_EDIT_K_SIZE                 1015
#define IDC_MFCBUTTON_FUN_HOUGHCIRCLE   1015
#define IDC_EDIT_EROSION_ITER           1016
#define IDC_BUTTON_APPLY_EROSION        1017
#define IDC_MFCBUTTON_ROTATE            1017
#define IDC_EDIT_DILATION_KERNAL1       1018
#define IDC_MFCBUTTON_ROTATE_CUDA       1018
#define IDC_EDIT_DILATION_KERNAL2       1019
#define IDC_MFCBUTTON_ROTATE2           1019
#define IDC_GRID_RESULT                 1019
#define IDC_EDIT_DILATION_ITER          1020
#define IDC_MFCBUTTON_ROTATE3           1020
#define IDC_STATIC_LAYOUT_IMG           1020
#define IDC_BUTTON_APPLY_DILATION       1021
#define IDC_MFCBUTTON_MORP              1021
#define IDC_EDIT_GAUSSIANBLUR_KSIZE     1022
#define IDC_EDIT_GAUSSIANBLUR_SIGMAX    1023
#define IDC_EDIT_GAUSSIANBLUR_SIGMAY    1024
#define IDC_BUTTON_APPLY_GAUSSIANBLUR   1025
#define IDC_EDIT_SOBEL_DEPTH            1026
#define IDC_EDIT_MEDIANBLUR_KSIZE       1027
#define IDC_BUTTON_APPLY_MEDIANBLUR     1028
#define IDC_BUTTON_APPLY_SOBEL          1029
#define IDC_BUTTON_APPLY_SOBEL_1        1030
#define IDC_EDIT_SOBEL_SCALE            1031
#define IDC_EDIT_SOBEL_DELTA            1032
#define IDC_COMBO_SOBEL_BORDERTYPE      1033
#define IDC_COMBO_SOBEL_DY              1034
#define IDC_COMBO_SOBEL_DX              1035
#define IDC_COMBO_SOBEL_KSIZE           1036
#define IDC_EDIT_GABER_KSIZE            1037
#define IDC_EDIT_GABER_SIGMA            1038
#define IDC_EDIT_GABER_THETA            1039
#define IDC_BUTTON_APPLY_GABER          1040
#define IDC_EDIT_GABER_LAMBDA           1041
#define IDC_EDIT_GABER_GAMMA            1042
#define IDC_EDIT_GABER_PSI              1043
#define IDC_BUTTON_APPLY_SOBEL_2        1044
#define IDC_BUTTON_APPLY_SCHARR         1045
#define IDC_BUTTON_APPLY_PREWITT        1046
#define IDC_BUTTON_APPLY_ROBERTS        1047
#define IDC_RADIO_GABER_KTYPE1          1048
#define IDC_RADIO_GABER_KTYPE2          1049
#define IDC_RADIO_SCHARR_AXIS_X         1050
#define IDC_RADIO_SCHARR_AXIS_Y         1051
#define IDC_RADIO_PREWITT_AXIS_X        1052
#define IDC_RADIO_PREWITT_AXIS_Y        1053
#define IDC_RADIO_ROBERTS_AXIS_X        1054
#define IDC_RADIO_ROBERTS_AXIS_Y        1055
#define IDC_RADIO_METHOD_1              1060
#define IDC_RADIO_METHOD_2              1061
#define IDC_RADIO_METHOD_3              1062
#define IDC_RADIO_METHOD_4              1063
#define IDC_RADIO_METHOD_5              1064
#define IDC_RADIO_METHOD_6              1065
#define IDC_RADIO_METHOD_7              1066
#define IDC_RADIO_METHOD_8              1067
#define ID_VIEW_IMAGE1                  32771
#define ID_VIEW_IMAGE2                  32772
#define ID_VIEW_IMAGE3                  32773
#define ID_VIEW_IMAGE4                  32774
#define ID_VIEW_IMAGE5                  32775
#define ID_VIEW_IMAGE6                  32776
#define ID_FILE                         32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
